/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN_COMMENT = 6;
  /** RegularExpression Id. */
  int END_COMMENT = 7;
  /** RegularExpression Id. */
  int COMMENT = 8;
  /** RegularExpression Id. */
  int BEGIN_MULT_COMMENT = 9;
  /** RegularExpression Id. */
  int END_MULT_COMMENT1 = 10;
  /** RegularExpression Id. */
  int MULT_COMMENT = 11;
  /** RegularExpression Id. */
  int ABSTRACT = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int BREAK = 14;
  /** RegularExpression Id. */
  int CASE = 15;
  /** RegularExpression Id. */
  int CATCH = 16;
  /** RegularExpression Id. */
  int CHAR = 17;
  /** RegularExpression Id. */
  int CLASS = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int DEFAULT1 = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int FINALLY = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int IMPLEMENTS = 29;
  /** RegularExpression Id. */
  int IMPORT = 30;
  /** RegularExpression Id. */
  int INSTANCEOF = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int INTERFACE = 33;
  /** RegularExpression Id. */
  int LONG = 34;
  /** RegularExpression Id. */
  int NEW = 35;
  /** RegularExpression Id. */
  int NULL = 36;
  /** RegularExpression Id. */
  int PACKAGE = 37;
  /** RegularExpression Id. */
  int PRIVATE = 38;
  /** RegularExpression Id. */
  int PROTECTED = 39;
  /** RegularExpression Id. */
  int PUBLIC = 40;
  /** RegularExpression Id. */
  int RETURN = 41;
  /** RegularExpression Id. */
  int STATIC = 42;
  /** RegularExpression Id. */
  int SUPER = 43;
  /** RegularExpression Id. */
  int SWITCH = 44;
  /** RegularExpression Id. */
  int THIS = 45;
  /** RegularExpression Id. */
  int THROW = 46;
  /** RegularExpression Id. */
  int THROWS = 47;
  /** RegularExpression Id. */
  int TRUE = 48;
  /** RegularExpression Id. */
  int TRY = 49;
  /** RegularExpression Id. */
  int VOID = 50;
  /** RegularExpression Id. */
  int WHILE = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int DOT = 53;
  /** RegularExpression Id. */
  int LBRACK = 54;
  /** RegularExpression Id. */
  int LCURLY = 55;
  /** RegularExpression Id. */
  int LPAREN = 56;
  /** RegularExpression Id. */
  int RPAREN = 57;
  /** RegularExpression Id. */
  int RBRACK = 58;
  /** RegularExpression Id. */
  int RCURLY = 59;
  /** RegularExpression Id. */
  int SEMI = 60;
  /** RegularExpression Id. */
  int QUESTION = 61;
  /** RegularExpression Id. */
  int COLON = 62;
  /** RegularExpression Id. */
  int ASSIGN = 63;
  /** RegularExpression Id. */
  int EQUAL = 64;
  /** RegularExpression Id. */
  int LNOT = 65;
  /** RegularExpression Id. */
  int BNOT = 66;
  /** RegularExpression Id. */
  int NOT_EQUAL = 67;
  /** RegularExpression Id. */
  int DIV = 68;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 69;
  /** RegularExpression Id. */
  int PLUS = 70;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 71;
  /** RegularExpression Id. */
  int INC = 72;
  /** RegularExpression Id. */
  int MINUS = 73;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 74;
  /** RegularExpression Id. */
  int DEC = 75;
  /** RegularExpression Id. */
  int STAR = 76;
  /** RegularExpression Id. */
  int STAR_ASSIGN = 77;
  /** RegularExpression Id. */
  int REM = 78;
  /** RegularExpression Id. */
  int REM_ASSIGN = 79;
  /** RegularExpression Id. */
  int ARSHIFT = 80;
  /** RegularExpression Id. */
  int ARSHIFT_ASSIGN = 81;
  /** RegularExpression Id. */
  int LRSHIFT = 82;
  /** RegularExpression Id. */
  int LRSHIFT_ASSIGN = 83;
  /** RegularExpression Id. */
  int GE = 84;
  /** RegularExpression Id. */
  int GT = 85;
  /** RegularExpression Id. */
  int ALSHIFT = 86;
  /** RegularExpression Id. */
  int ALSHIFT_ASSIGN = 87;
  /** RegularExpression Id. */
  int LE = 88;
  /** RegularExpression Id. */
  int LT = 89;
  /** RegularExpression Id. */
  int BXOR = 90;
  /** RegularExpression Id. */
  int BXOR_ASSIGN = 91;
  /** RegularExpression Id. */
  int BOR = 92;
  /** RegularExpression Id. */
  int BOR_ASSIGN = 93;
  /** RegularExpression Id. */
  int LOR = 94;
  /** RegularExpression Id. */
  int BAND = 95;
  /** RegularExpression Id. */
  int BAND_ASSIGN = 96;
  /** RegularExpression Id. */
  int LAND = 97;
  /** RegularExpression Id. */
  int IDENTIFIER = 98;
  /** RegularExpression Id. */
  int LETTER = 99;
  /** RegularExpression Id. */
  int DIGIT = 100;
  /** RegularExpression Id. */
  int INT_LITERAL = 101;
  /** RegularExpression Id. */
  int LONG_LITERAL = 102;
  /** RegularExpression Id. */
  int EXPONENT = 103;
  /** RegularExpression Id. */
  int SUFFIX = 104;
  /** RegularExpression Id. */
  int DOUBLE_LITERAL = 105;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 106;
  /** RegularExpression Id. */
  int STRING_LITERAL = 107;
  /** RegularExpression Id. */
  int ESC = 108;
  /** RegularExpression Id. */
  int ERROR = 109;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int MULTILINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<END_COMMENT>",
    "<COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<MULT_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"finally\"",
    "\"for\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"{\"",
    "\"(\"",
    "\")\"",
    "\"]\"",
    "\"}\"",
    "\";\"",
    "\"?\"",
    "\":\"",
    "\"=\"",
    "\"==\"",
    "\"!\"",
    "\"~\"",
    "\"!=\"",
    "\"/\"",
    "\"/=\"",
    "\"+\"",
    "\"+=\"",
    "\"++\"",
    "\"-\"",
    "\"-=\"",
    "\"--\"",
    "\"*\"",
    "\"*=\"",
    "\"%\"",
    "\"%=\"",
    "\">>\"",
    "\">>=\"",
    "\">>>\"",
    "\">>>=\"",
    "\">=\"",
    "\">\"",
    "\"<<\"",
    "\"<<=\"",
    "\"<=\"",
    "\"<\"",
    "\"^\"",
    "\"^=\"",
    "\"|\"",
    "\"|=\"",
    "\"||\"",
    "\"&\"",
    "\"&=\"",
    "\"&&\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INT_LITERAL>",
    "<LONG_LITERAL>",
    "<EXPONENT>",
    "<SUFFIX>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
